security:
    encoders:
        Symfony\Component\Security\Core\User\User: 
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
        Sevdev\ArkonTestBundle\Entity\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider: 
            providers: [in_memory, database]

        # Hardcoded superadmin with login admin:admin,
        # and user as user:user
        # Only available in development mode
        
        in_memory: 
            users:
                admin: 
                    password: d033e22ae348aeb5660fc2140aec35850c4da997
                    roles: [ROLE_SUPER_ADMIN]
                user:
                    password: 12dea96fec20593566ab75692c9949596833adc9
                    roles: [ROLE_USER]
        database:
            entity: 
                class: Sevdev\ArkonTestBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/login$
            anonymous: ~
            security: false
        main:
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /login_check
            logout: 
              path: /logout
              target: /login

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONIMOUSLY }
        - { path: ^/, roles: ROLE_USER }
